@{
    SchemaVersion = '1.0'
    ManifestKind = 'RuntimeOperationDescriptors'
    ManifestPurpose = 'Generated operation descriptor boundary for future external package generation.'
    GeneratedFromCommit = '26237e4'
    GeneratedFromCommitSubject = 'Audit external source intent readiness'
    GeneratedAt = 'Static Phase 175J foundation record; future phases may replace this with generated descriptor output.'
    CustomerVisible = $false
    DefaultMode = 'InternalDevelopment'
    ExternalRuntimeStatus = 'DescriptorCoverageAvailableModuleDecouplingStillBlocked'
    RequiredSourceIntentBlockers = @(
        'reinstall.source'
        'updates-drivers-block.source'
        'bitlocker.source'
        'convert-home-to-pro.source'
        'edge-settings.source'
        'installers.source'
        'driver-clean.source'
        'nvidia-app-install.source'
        'directx.source'
        'visual-cpp.source'
        'bloatware.source'
        'copilot.source'
        'game-bar.source'
        'edge-webview.source'
        'control-panel-settings.source'
        'cleanup.source'
    )
    Entries = @{
        'reinstall-operation-summary' = @{
            DescriptorId = 'reinstall-operation-summary'
            ToolId = 'reinstall'
            ToolTitle = 'Reinstall'
            Stage = 'Refresh'
            SourceIntentId = 'reinstall.source'
            ModuleRelativePath = 'modules/Refresh/reinstall.psm1'
            SourceRawSha256 = '137F519926293F37052817ACBBE20851652E5EA1B9F3B5B9F933AA1E22C2D9FB'
            SourceCanonicalTextSha256 = '64F76A856E4CC57BEE34C6DEA86F2B7ADC432B01A3FA4AEB5C2A650B9AE9A477'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Open', 'Apply', 'Default', 'Restore')
            Branches = @('Windows media preparation handoff', 'selected media creation launch', 'download preparation check')
            OperationCategories = @('MediaPreparation', 'ExternalToolLaunch', 'DownloadPreparation', 'ActionPlanSupport')
            OperationCount = 4
            OperationSummary = 'Summarizes media preparation, download planning, and launch handoff evidence for the Refresh reinstall workflow.'
            Capabilities = @{
                CanDeleteFiles = $false
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $false
                CanModifySecurity = $false
                CanModifyServices = $false
                CanReboot = $true
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor summarizes approved operation categories only; current module still uses internal parity checks before action flow.'
        }
        'updates-drivers-block-operation-summary' = @{
            DescriptorId = 'updates-drivers-block-operation-summary'
            ToolId = 'updates-drivers-block'
            ToolTitle = 'Updates Drivers Block'
            Stage = 'Refresh'
            SourceIntentId = 'updates-drivers-block.source'
            ModuleRelativePath = 'modules/Refresh/updates-drivers-block.psm1'
            SourceRawSha256 = '4D4EC652C5A7F78824F53B7DC7FD46DDA948F3716A7CD6FD102D6C678EE11991'
            SourceCanonicalTextSha256 = 'D18878A8856096913643F7619917CAE688A19368A34792D94F3CC53BE45B0367'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Apply', 'Default', 'Restore')
            Branches = @('removable media setup script generation', 'selected USB state capture', 'driver update policy script')
            OperationCategories = @('UsbMediaPreparation', 'SetupCompleteScript', 'DriverUpdatePolicy', 'FileWrite')
            OperationCount = 4
            OperationSummary = 'Summarizes removable-media setup-script planning and selected USB file-state evidence for the driver-update block workflow.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $false
                CanInstallSoftware = $false
                CanModifyDrivers = $false
                CanModifyRegistry = $false
                CanModifySecurity = $false
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $false
                SupportsDefault = $false
                SupportsRestore = $true
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records the USB setup-script workflow only; current module still uses internal parity checks before action flow.'
        }
        'bitlocker-operation-summary' = @{
            DescriptorId = 'bitlocker-operation-summary'
            ToolId = 'bitlocker'
            ToolTitle = 'BitLocker'
            Stage = 'Setup'
            SourceIntentId = 'bitlocker.source'
            ModuleRelativePath = 'modules/Setup/bitlocker.psm1'
            SourceRawSha256 = '1678E97FB5AFF851F1491A2D96C82A5716B1FA07CB4E3A4A5E0F3FB1B086FBA1'
            SourceCanonicalTextSha256 = '1678E97FB5AFF851F1491A2D96C82A5716B1FA07CB4E3A4A5E0F3FB1B086FBA1'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Apply', 'Default', 'Restore', 'Open')
            Branches = @('volume status inspection', 'control panel handoff', 'managed disable request')
            OperationCategories = @('SecurityAssistant', 'VolumeInspection', 'ControlPanelLaunch', 'BitLockerDisable')
            OperationCount = 4
            OperationSummary = 'Summarizes volume-encryption status evidence, control-panel handoff, and guarded security-assistant actions.'
            Capabilities = @{
                CanDeleteFiles = $false
                CanDownload = $false
                CanInstallSoftware = $false
                CanModifyDrivers = $false
                CanModifyRegistry = $false
                CanModifySecurity = $true
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $false
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records security workflow metadata only; current module still uses internal parity checks before action flow.'
        }
        'convert-home-to-pro-operation-summary' = @{
            DescriptorId = 'convert-home-to-pro-operation-summary'
            ToolId = 'convert-home-to-pro'
            ToolTitle = 'Convert Home To Pro'
            Stage = 'Setup'
            SourceIntentId = 'convert-home-to-pro.source'
            ModuleRelativePath = 'modules/Setup/convert-home-to-pro.psm1'
            SourceRawSha256 = '3B779A75960FB724A2F5FF756FCEDD1CF6897D0021FD6DBE1D671189CBA57924'
            SourceCanonicalTextSha256 = '3B779A75960FB724A2F5FF756FCEDD1CF6897D0021FD6DBE1D671189CBA57924'
            DescriptorKind = 'OperationSummary'
            Actions = @('Apply')
            Branches = @('edition conversion preparation', 'activation settings handoff', 'network guidance')
            OperationCategories = @('EditionUpgradePreparation', 'ActivationSettings', 'NetworkGuidance', 'ManualKeyFlow')
            OperationCount = 4
            OperationSummary = 'Summarizes edition-conversion preparation, activation-setting handoff, and technician guidance evidence.'
            Capabilities = @{
                CanDeleteFiles = $false
                CanDownload = $false
                CanInstallSoftware = $false
                CanModifyDrivers = $false
                CanModifyRegistry = $false
                CanModifySecurity = $true
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $false
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records edition workflow metadata only; current module still uses internal parity checks before action flow.'
        }
        'edge-settings-operation-summary' = @{
            DescriptorId = 'edge-settings-operation-summary'
            ToolId = 'edge-settings'
            ToolTitle = 'Edge Settings'
            Stage = 'Setup'
            SourceIntentId = 'edge-settings.source'
            ModuleRelativePath = 'modules/Setup/edge-settings.psm1'
            SourceRawSha256 = '342869157930ECF0869A07B4254CB8F174C63648CD329DB3914BAD291CD5FF28'
            SourceCanonicalTextSha256 = '3EE9E6F586D71E74F7400379E8D5DA079D52208D5B2DFA0E4AB035FCB08096A8'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Apply', 'Default', 'Restore')
            Branches = @('optimize browser policy', 'default browser repair', 'service and task cleanup', 'downloaded repair flow')
            OperationCategories = @('BrowserPolicy', 'RegistryMutation', 'ServiceCleanup', 'ScheduledTaskCleanup', 'InstallerRepair', 'Download')
            OperationCount = 6
            OperationSummary = 'Summarizes browser policy, cleanup, repair, and download-plan categories for the Edge Settings workflow.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $false
                CanModifyServices = $true
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $true
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records browser workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'installers-operation-summary' = @{
            DescriptorId = 'installers-operation-summary'
            ToolId = 'installers'
            ToolTitle = 'Installers'
            Stage = 'Installers'
            SourceIntentId = 'installers.source'
            ModuleRelativePath = 'modules/Installers/installers.psm1'
            SourceRawSha256 = '1065D64183457D4E7B28EA78DDE41525EC8F7C4A4BCA12D29B70D991141C0C67'
            SourceCanonicalTextSha256 = '268C1EFE627FADDA17892223D4C35E4845833506C22AADD3240C894ED046A6F8'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Open', 'Apply', 'Default', 'Restore')
            Branches = @('retained installer catalog', 'download plan', 'installer execution', 'post-install configuration')
            OperationCategories = @('InstallerCatalog', 'ArtifactDownload', 'InstallerExecution', 'PostInstallConfiguration')
            OperationCount = 4
            OperationSummary = 'Summarizes retained installer catalog entries, download requirements, execution sequence, and post-install operations.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $false
                CanModifyServices = $true
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records installer workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'driver-clean-operation-summary' = @{
            DescriptorId = 'driver-clean-operation-summary'
            ToolId = 'driver-clean'
            ToolTitle = 'Driver Clean'
            Stage = 'Graphics'
            SourceIntentId = 'driver-clean.source'
            ModuleRelativePath = 'modules/Graphics/driver-clean.psm1'
            SourceRawSha256 = 'CF9E1C55ACAFD8A52D2200AC3E6C3AFDF9823837C7B68101C2D4B83E074D325A'
            SourceCanonicalTextSha256 = 'CF9E1C55ACAFD8A52D2200AC3E6C3AFDF9823837C7B68101C2D4B83E074D325A'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Open', 'Apply')
            Branches = @('automatic graphics cleanup', 'manual graphics cleanup', 'safe-mode preparation', 'restart planning')
            OperationCategories = @('DriverCleanup', 'SafeModeWorkflow', 'PreparationDownload', 'RunOncePlan', 'RebootPreparation')
            OperationCount = 5
            OperationSummary = 'Summarizes graphics-driver cleanup branches, safe-mode preparation, restart planning, and artifact requirements.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $true
                CanModifyRegistry = $true
                CanModifySecurity = $false
                CanModifyServices = $false
                CanReboot = $true
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $true
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records approved Driver Clean workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'nvidia-app-install-operation-summary' = @{
            DescriptorId = 'nvidia-app-install-operation-summary'
            ToolId = 'nvidia-app-install'
            ToolTitle = 'Install NVIDIA App'
            Stage = 'Graphics'
            SourceIntentId = 'nvidia-app-install.source'
            ModuleRelativePath = 'modules/Graphics/nvidia-app-install.psm1'
            SourceRawSha256 = '1065D64183457D4E7B28EA78DDE41525EC8F7C4A4BCA12D29B70D991141C0C67'
            SourceCanonicalTextSha256 = '268C1EFE627FADDA17892223D4C35E4845833506C22AADD3240C894ED046A6F8'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Apply')
            Branches = @('NVIDIA app installer', 'download plan', 'installer execution', 'shortcut cleanup')
            OperationCategories = @('NvidiaInstaller', 'ArtifactDownload', 'InstallerExecution', 'ShortcutCleanup')
            OperationCount = 4
            OperationSummary = 'Summarizes NVIDIA app download, installer execution, and post-install cleanup categories.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $false
                CanModifySecurity = $false
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records NVIDIA installer workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'directx-operation-summary' = @{
            DescriptorId = 'directx-operation-summary'
            ToolId = 'directx'
            ToolTitle = 'DirectX'
            Stage = 'Graphics'
            SourceIntentId = 'directx.source'
            ModuleRelativePath = 'modules/Graphics/directx.psm1'
            SourceRawSha256 = '17051A2F0F7A0CF16BE525121720406E8F1630C94E5977A7CD4C18652A87EE05'
            SourceCanonicalTextSha256 = 'B944AE03DE0AFDD7329B84BBF53FF5624739465CBB7130A021E097A6723B1B27'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Apply')
            Branches = @('DirectX package acquisition', 'archive extraction', 'installer execution', 'temporary artifact cleanup')
            OperationCategories = @('DirectXPackage', 'ArchiveExtraction', 'InstallerExecution', 'ArtifactDownload', 'TemporaryFileCleanup')
            OperationCount = 5
            OperationSummary = 'Summarizes DirectX package acquisition, extraction, installer execution, and temporary-file cleanup categories.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $false
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records DirectX workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'visual-cpp-operation-summary' = @{
            DescriptorId = 'visual-cpp-operation-summary'
            ToolId = 'visual-cpp'
            ToolTitle = 'Visual C++'
            Stage = 'Graphics'
            SourceIntentId = 'visual-cpp.source'
            ModuleRelativePath = 'modules/Graphics/visual-cpp.psm1'
            SourceRawSha256 = '7ACB1F25ECFEEAD83FA389E2D0C1FEEF12232C4E9A740CB5DE64A326FFD38C09'
            SourceCanonicalTextSha256 = '01D6A5FAFD5E7C1FB9DA1913BD17C543EE0F8A4A7E2A7DF5583A50AEF1D82374'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Apply')
            Branches = @('redistributable catalog', 'sequential download plan', 'waited installer execution')
            OperationCategories = @('RedistributableInstallers', 'ArtifactDownload', 'SequentialInstallerExecution')
            OperationCount = 3
            OperationSummary = 'Summarizes redistributable package selection, download plan, and sequential installer execution categories.'
            Capabilities = @{
                CanDeleteFiles = $false
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $false
                CanModifySecurity = $false
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records Visual C++ workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'bloatware-operation-summary' = @{
            DescriptorId = 'bloatware-operation-summary'
            ToolId = 'bloatware'
            ToolTitle = 'Bloatware'
            Stage = 'Windows'
            SourceIntentId = 'bloatware.source'
            ModuleRelativePath = 'modules/Windows/bloatware.psm1'
            SourceRawSha256 = '36677A334B37025A7234F4320EE54EF50E9528D1814E2B3A463EEB564C5814F5'
            SourceCanonicalTextSha256 = 'EBCE09158AB61ADE2C181DD5DB64C94B962BAF133DB4DB6122CEE642B9A48C9F'
            DescriptorKind = 'OperationSummary'
            Actions = @('Analyze', 'Apply')
            Branches = @('package removal catalog', 'service cleanup', 'policy update', 'feature repair')
            OperationCategories = @('PackageInventory', 'ServiceCleanup', 'RegistryPolicy', 'FeatureRepair', 'BranchCatalog')
            OperationCount = 5
            OperationSummary = 'Summarizes package inventory, cleanup, policy, feature repair, and branch-catalog categories for the Bloatware workflow.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $true
                CanModifyServices = $true
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records bloatware workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'copilot-operation-summary' = @{
            DescriptorId = 'copilot-operation-summary'
            ToolId = 'copilot'
            ToolTitle = 'Copilot'
            Stage = 'Windows'
            SourceIntentId = 'copilot.source'
            ModuleRelativePath = 'modules/Windows/copilot.psm1'
            SourceRawSha256 = '21B58212B241A6C0B74582063E3E74F746014E9137194B58B088CC6692F22A90'
            SourceCanonicalTextSha256 = '45F87252A018398E87B281DE094E4943A63026567EB0782B631BBEF989CF6A9E'
            DescriptorKind = 'OperationSummary'
            Actions = @('Apply', 'Default')
            Branches = @('assistant removal', 'assistant restore', 'policy update', 'process stop')
            OperationCategories = @('PackageRemoval', 'PackageRestore', 'RegistryPolicy', 'ProcessStop')
            OperationCount = 4
            OperationSummary = 'Summarizes assistant package removal, restore, policy, and process-stop categories.'
            Capabilities = @{
                CanDeleteFiles = $false
                CanDownload = $false
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $true
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $false
                SupportsDefault = $true
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records assistant workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'game-bar-operation-summary' = @{
            DescriptorId = 'game-bar-operation-summary'
            ToolId = 'game-bar'
            ToolTitle = 'GameBar'
            Stage = 'Windows'
            SourceIntentId = 'game-bar.source'
            ModuleRelativePath = 'modules/Windows/game-bar.psm1'
            SourceRawSha256 = '8C6703E68C251D63ADD81A87B7CB6C1F572A4CE55A1E092C33B9B444A9884E59'
            SourceCanonicalTextSha256 = 'C35831AFE527DFA090E5DA6EBF0F6132256A4ABF3BEBDA90FC8605C47F55C0D2'
            DescriptorKind = 'OperationSummary'
            Actions = @('Apply', 'Default')
            Branches = @('gaming app policy', 'gaming service repair', 'package removal', 'trusted repair flow')
            OperationCategories = @('GamingAppPolicy', 'RegistryPolicy', 'PackageRepair', 'ServiceCleanup', 'TrustedRepairFlow')
            OperationCount = 5
            OperationSummary = 'Summarizes gaming policy, package repair, service cleanup, and trusted repair-flow categories.'
            Capabilities = @{
                CanDeleteFiles = $false
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $true
                CanModifyServices = $true
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $true
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $true
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records GameBar workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'edge-webview-operation-summary' = @{
            DescriptorId = 'edge-webview-operation-summary'
            ToolId = 'edge-webview'
            ToolTitle = 'Edge & WebView'
            Stage = 'Windows'
            SourceIntentId = 'edge-webview.source'
            ModuleRelativePath = 'modules/Windows/edge-webview.psm1'
            SourceRawSha256 = '161ED9C99D437E45650369CB7E15D5737DED363712E647138F134B049AC7E691'
            SourceCanonicalTextSha256 = '3AB92D76307B1CB4C6988DB2201631C14D3B91B32CFFA4F1177B3E1F4F0D7966'
            DescriptorKind = 'OperationSummary'
            Actions = @('Apply', 'Default')
            Branches = @('browser runtime removal', 'browser runtime repair', 'process stop', 'service cleanup')
            OperationCategories = @('BrowserRuntimeRemoval', 'InstallerRepair', 'ProcessStop', 'ServiceCleanup', 'ArtifactDownload')
            OperationCount = 5
            OperationSummary = 'Summarizes browser-runtime removal, repair, process-stop, service-cleanup, and download categories.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $true
                CanInstallSoftware = $true
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $true
                CanModifyServices = $true
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $true
                SupportsDefault = $true
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records Edge and WebView workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'control-panel-settings-operation-summary' = @{
            DescriptorId = 'control-panel-settings-operation-summary'
            ToolId = 'control-panel-settings'
            ToolTitle = 'Control Panel Settings'
            Stage = 'Windows'
            SourceIntentId = 'control-panel-settings.source'
            ModuleRelativePath = 'modules/Windows/control-panel-settings.psm1'
            SourceRawSha256 = 'B78F643D21069F14E7E766769FB1EE15AEF974ABDF3CA010FE808D9EC162FB0B'
            SourceCanonicalTextSha256 = 'F81FB649A4645A5145B43A051DDF8306145E64F1FCA5249F90B66BFDFA97BE83'
            DescriptorKind = 'OperationSummary'
            Actions = @('Apply', 'Default')
            Branches = @('control panel policy apply', 'control panel policy default', 'trusted service handling', 'settings restore')
            OperationCategories = @('RegistryPolicy', 'ControlPanelPolicy', 'SecurityPolicy', 'ServiceCleanup', 'TrustedRepairFlow')
            OperationCount = 5
            OperationSummary = 'Summarizes Control Panel policy, security policy, service handling, and trusted repair-flow categories.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $false
                CanInstallSoftware = $false
                CanModifyDrivers = $false
                CanModifyRegistry = $true
                CanModifySecurity = $true
                CanModifyServices = $true
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $false
                SupportsDefault = $true
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $true
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records Control Panel Settings workflow categories only; current module still uses internal parity checks before action flow.'
        }
        'cleanup-operation-summary' = @{
            DescriptorId = 'cleanup-operation-summary'
            ToolId = 'cleanup'
            ToolTitle = 'Cleanup'
            Stage = 'Windows'
            SourceIntentId = 'cleanup.source'
            ModuleRelativePath = 'modules/Windows/cleanup.psm1'
            SourceRawSha256 = '3419A995AD4483A145999B659268302F02BE982733DE831554ADA1C40F07CCAA'
            SourceCanonicalTextSha256 = '13C3933AC95A9817E48C0FFA4971FB2CC2234F9783831C34675F9F529F2D507E'
            DescriptorKind = 'OperationSummary'
            Actions = @('Apply')
            Branches = @('temporary file cleanup', 'legacy install cleanup', 'system dump cleanup', 'disk cleanup handoff')
            OperationCategories = @('CleanupTargets', 'TemporaryFileCleanup', 'WindowsOldCleanup', 'SystemDumpCleanup', 'DiskCleanupLaunch')
            OperationCount = 5
            OperationSummary = 'Summarizes cleanup target categories, temporary-file handling, legacy install cleanup, dump cleanup, and disk-cleanup handoff.'
            Capabilities = @{
                CanDeleteFiles = $true
                CanDownload = $false
                CanInstallSoftware = $false
                CanModifyDrivers = $false
                CanModifyRegistry = $false
                CanModifySecurity = $false
                CanModifyServices = $false
                CanReboot = $false
                NeedsExplicitConfirmation = $true
                RequiresAdmin = $true
                RequiresInternet = $false
                SupportsDefault = $false
                SupportsRestore = $false
                UsesSafeMode = $false
                UsesTrustedInstaller = $false
            }
            RuntimeUse = @('ExternalRuntimeEvidence', 'ActionPlanSupport', 'DevelopmentSourceParityReference', 'DiagnosticsOnly')
            ExternalHandling = 'OperationDescriptorAvailable'
            ExternalModeTreatment = @('DescriptorOnly', 'ExternalRuntimeCanExcludeRawSource', 'ExternalRuntimeStillNeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            RuntimeWiringStatus = 'ReadyForFutureExternalMode'
            ModuleRuntimeWiringStatus = 'NotWired'
            CustomerVisible = $false
            RuntimeActionExecuted = $false
            ChangesExecuted = $false
            Notes = 'Static descriptor records cleanup workflow categories only; current module still uses internal parity checks before action flow.'
        }
    }
}
