@{
    SchemaVersion = '1.0'
    ManifestPurpose = 'Runtime source intent boundary for future external package generation.'
    GeneratedFromCommit = '55536fd'
    GeneratedFromCommitSubject = 'Add external runtime package decoupling plan'
    GeneratedAt = 'Static Phase 175C foundation record; future phases may replace this with generated manifest output.'
    CustomerVisible = $false
    DefaultMode = 'InternalDevelopment'
    ExternalRuntimeStatus = 'GeneratedPayloadIntentsReadyOtherSourceDependenciesBlocked'
    Entries = @{
        'reinstall.source' = @{
            SourceId = 'reinstall-source'
            ToolId = 'reinstall'
            ModuleRelativePath = 'modules/Refresh/reinstall.psm1'
            SourceRelativePath = 'source-ultimate/2 Refresh/1 Reinstall.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '137F519926293F37052817ACBBE20851652E5EA1B9F3B5B9F933AA1E22C2D9FB'
            CanonicalTextSha256 = '64F76A856E4CC57BEE34C6DEA86F2B7ADC432B01A3FA4AEB5C2A650B9AE9A477'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'reinstall-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source path before the action path can proceed.'
        }
        'updates-drivers-block.source' = @{
            SourceId = 'updates-drivers-block-source'
            ToolId = 'updates-drivers-block'
            ModuleRelativePath = 'modules/Refresh/updates-drivers-block.psm1'
            SourceRelativePath = 'source-ultimate/2 Refresh/3 Updates Drivers Block.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '4D4EC652C5A7F78824F53B7DC7FD46DDA948F3716A7CD6FD102D6C678EE11991'
            CanonicalTextSha256 = 'D18878A8856096913643F7619917CAE688A19368A34792D94F3CC53BE45B0367'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'updates-drivers-block-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source path before creating the selected USB setup script.'
        }
        'bitlocker.source' = @{
            SourceId = 'bitlocker-source'
            ToolId = 'bitlocker'
            ModuleRelativePath = 'modules/Setup/bitlocker.psm1'
            SourceRelativePath = 'source-ultimate/_intake-promoted/Ultimate/3 Setup/1 BitLocker.ps1'
            SourceRole = 'SourcePromotedIntake'
            RawSha256 = '1678E97FB5AFF851F1491A2D96C82A5716B1FA07CB4E3A4A5E0F3FB1B086FBA1'
            CanonicalTextSha256 = '1678E97FB5AFF851F1491A2D96C82A5716B1FA07CB4E3A4A5E0F3FB1B086FBA1'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'bitlocker-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies the source-promoted setup source before reporting security assistant actions.'
        }
        'convert-home-to-pro.source' = @{
            SourceId = 'convert-home-to-pro-source'
            ToolId = 'convert-home-to-pro'
            ModuleRelativePath = 'modules/Setup/convert-home-to-pro.psm1'
            SourceRelativePath = 'source-extra/forgotten-scripts/3 Convert Home To Pro.ps1'
            SourceRole = 'SourceExtra'
            RawSha256 = '3B779A75960FB724A2F5FF756FCEDD1CF6897D0021FD6DBE1D671189CBA57924'
            CanonicalTextSha256 = '3B779A75960FB724A2F5FF756FCEDD1CF6897D0021FD6DBE1D671189CBA57924'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'convert-home-to-pro-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies the protected extra source before preparing the edition conversion flow.'
        }
        'edge-settings.source' = @{
            SourceId = 'edge-settings-source'
            ToolId = 'edge-settings'
            ModuleRelativePath = 'modules/Setup/edge-settings.psm1'
            SourceRelativePath = 'source-ultimate/3 Setup/6 Edge Settings.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '342869157930ECF0869A07B4254CB8F174C63648CD329DB3914BAD291CD5FF28'
            CanonicalTextSha256 = '3EE9E6F586D71E74F7400379E8D5DA079D52208D5B2DFA0E4AB035FCB08096A8'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'edge-settings-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before Edge settings action planning and execution.'
        }
        'installers.source' = @{
            SourceId = 'installers-source'
            ToolId = 'installers'
            ModuleRelativePath = 'modules/Installers/installers.psm1'
            SourceRelativePath = 'source-ultimate/4 Installers/1 Installers.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '1065D64183457D4E7B28EA78DDE41525EC8F7C4A4BCA12D29B70D991141C0C67'
            CanonicalTextSha256 = '268C1EFE627FADDA17892223D4C35E4845833506C22AADD3240C894ED046A6F8'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'installers-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before retained installer catalog actions.'
        }
        'driver-clean.source' = @{
            SourceId = 'driver-clean-source'
            ToolId = 'driver-clean'
            ModuleRelativePath = 'modules/Graphics/driver-clean.psm1'
            SourceRelativePath = 'source-ultimate/_intake-promoted/Ultimate/5 Graphics/1 Driver Clean.ps1'
            SourceRole = 'SourcePromotedIntake'
            RawSha256 = 'CF9E1C55ACAFD8A52D2200AC3E6C3AFDF9823837C7B68101C2D4B83E074D325A'
            CanonicalTextSha256 = 'CF9E1C55ACAFD8A52D2200AC3E6C3AFDF9823837C7B68101C2D4B83E074D325A'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'driver-clean-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies the source-promoted graphics cleanup source before action planning.'
        }
        'driver-install-debloat-settings.source' = @{
            SourceId = 'driver-install-debloat-settings-source'
            ToolId = 'driver-install-debloat-settings'
            ModuleRelativePath = 'modules/Graphics/driver-install-debloat-settings.psm1'
            SourceRelativePath = 'source-ultimate/5 Graphics/1 Driver Install Debloat & Settings.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = 'E69EFF538E7CE6108233C525A2BB88BA2D549CE6954AE751BE7BED778271C26F'
            CanonicalTextSha256 = '00D7EA2C941DF776F729CD35A9386FE18D59D02717DCB3CF43282714E345A6D3'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimePayloadGeneration', 'RuntimeVerification')
            ExternalHandling = 'ManifestOnly'
            ExternalModeTreatment = @('ManifestOnly', 'RuntimePayloadReady', 'DevelopmentOnlySourceParity', 'ExternalRuntimeCanExcludeSource')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @(
                @{
                    PayloadId = 'driver-install-debloat-settings-nvidia-profile'
                    PayloadKind = 'Text'
                    HashMode = 'CanonicalText'
                    RuntimePayloadRelativePath = 'runtime-payloads/driver-install-debloat-settings/inspector.nip'
                    RuntimeWiringStatus = 'ReadyForExternalRuntime'
                    ExpectedSha256 = '8843CA82507C858A3A204883B71E791275BAC6F6EAAA2EAADBA02CDB3D1A242B'
                    ExpectedLength = 7712
                    ExternalHandling = 'GeneratedRuntimePayloadAvailable'
                    Notes = 'The NVIDIA profile payload is now available as a generated runtime payload; protected source remains internal-development parity/provenance input.'
                }
            )
            Notes = 'External runtime can use the generated NVIDIA profile payload; internal development still records the protected source for parity and provenance.'
        }
        'nvidia-app-install.source' = @{
            SourceId = 'nvidia-app-install-source'
            ToolId = 'nvidia-app-install'
            ModuleRelativePath = 'modules/Graphics/nvidia-app-install.psm1'
            SourceRelativePath = 'source-ultimate/4 Installers/1 Installers.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '1065D64183457D4E7B28EA78DDE41525EC8F7C4A4BCA12D29B70D991141C0C67'
            CanonicalTextSha256 = '268C1EFE627FADDA17892223D4C35E4845833506C22AADD3240C894ED046A6F8'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'nvidia-app-install-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies the installer source identity for the graphics-scoped app install flow.'
        }
        'directx.source' = @{
            SourceId = 'directx-source'
            ToolId = 'directx'
            ModuleRelativePath = 'modules/Graphics/directx.psm1'
            SourceRelativePath = 'source-ultimate/5 Graphics/2 DirectX.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '17051A2F0F7A0CF16BE525121720406E8F1630C94E5977A7CD4C18652A87EE05'
            CanonicalTextSha256 = 'B944AE03DE0AFDD7329B84BBF53FF5624739465CBB7130A021E097A6723B1B27'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'directx-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before DirectX action planning.'
        }
        'visual-cpp.source' = @{
            SourceId = 'visual-cpp-source'
            ToolId = 'visual-cpp'
            ModuleRelativePath = 'modules/Graphics/visual-cpp.psm1'
            SourceRelativePath = 'source-ultimate/5 Graphics/3 C++.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '7ACB1F25ECFEEAD83FA389E2D0C1FEEF12232C4E9A740CB5DE64A326FFD38C09'
            CanonicalTextSha256 = '01D6A5FAFD5E7C1FB9DA1913BD17C543EE0F8A4A7E2A7DF5583A50AEF1D82374'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'visual-cpp-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before Visual C++ action planning.'
        }
        'start-menu-taskbar.source' = @{
            SourceId = 'start-menu-taskbar-source'
            ToolId = 'start-menu-taskbar'
            ModuleRelativePath = 'modules/Windows/start-menu-taskbar.psm1'
            SourceRelativePath = 'source-ultimate/6 Windows/1 Start Menu Taskbar.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '88BEB0E8C41F7A32AAE6A0A6E184E87E678FB25BEDEB092C63F4BA98B8712E91'
            CanonicalTextSha256 = 'D53678CE91FE8ADE6D28F221A2E4153188597D850149F87227B26E0B821EFFF4'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimePayloadGeneration', 'RuntimeVerification')
            ExternalHandling = 'ManifestOnly'
            ExternalModeTreatment = @('ManifestOnly', 'RuntimePayloadReady', 'DevelopmentOnlySourceParity', 'ExternalRuntimeCanExcludeSource')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @(
                @{
                    PayloadId = 'start-menu-taskbar-start2-bin'
                    PayloadKind = 'Binary'
                    HashMode = 'RawBytes'
                    RuntimePayloadRelativePath = 'runtime-payloads/start-menu-taskbar/start2.bin'
                    RuntimeWiringStatus = 'ReadyForExternalRuntime'
                    ExpectedSha256 = '21EAF7925A26A59880D799509C5E49D4034B36BD86D84D035A50D17D6A32206D'
                    ExpectedLength = 4540
                    ExternalHandling = 'GeneratedRuntimePayloadAvailable'
                    Notes = 'The start2.bin payload is now available as a generated runtime payload; protected source remains internal-development parity/provenance input.'
                }
            )
            Notes = 'External runtime can use the generated start2.bin payload; internal development still records the protected source for parity and provenance.'
        }
        'bloatware.source' = @{
            SourceId = 'bloatware-source'
            ToolId = 'bloatware'
            ModuleRelativePath = 'modules/Windows/bloatware.psm1'
            SourceRelativePath = 'source-ultimate/6 Windows/11 Bloatware.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '36677A334B37025A7234F4320EE54EF50E9528D1814E2B3A463EEB564C5814F5'
            CanonicalTextSha256 = 'EBCE09158AB61ADE2C181DD5DB64C94B962BAF133DB4DB6122CEE642B9A48C9F'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'bloatware-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before bloatware branch planning.'
        }
        'copilot.source' = @{
            SourceId = 'copilot-source'
            ToolId = 'copilot'
            ModuleRelativePath = 'modules/Windows/copilot.psm1'
            SourceRelativePath = 'source-ultimate/6 Windows/8 Copilot.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '21B58212B241A6C0B74582063E3E74F746014E9137194B58B088CC6692F22A90'
            CanonicalTextSha256 = '45F87252A018398E87B281DE094E4943A63026567EB0782B631BBEF989CF6A9E'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'copilot-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before Copilot action planning.'
        }
        'game-bar.source' = @{
            SourceId = 'game-bar-source'
            ToolId = 'game-bar'
            ModuleRelativePath = 'modules/Windows/game-bar.psm1'
            SourceRelativePath = 'source-ultimate/6 Windows/12 Gamebar.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '8C6703E68C251D63ADD81A87B7CB6C1F572A4CE55A1E092C33B9B444A9884E59'
            CanonicalTextSha256 = 'C35831AFE527DFA090E5DA6EBF0F6132256A4ABF3BEBDA90FC8605C47F55C0D2'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'game-bar-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before GameBar action planning.'
        }
        'edge-webview.source' = @{
            SourceId = 'edge-webview-source'
            ToolId = 'edge-webview'
            ModuleRelativePath = 'modules/Windows/edge-webview.psm1'
            SourceRelativePath = 'source-ultimate/6 Windows/13 Edge & WebView.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '161ED9C99D437E45650369CB7E15D5737DED363712E647138F134B049AC7E691'
            CanonicalTextSha256 = '3AB92D76307B1CB4C6988DB2201631C14D3B91B32CFFA4F1177B3E1F4F0D7966'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'edge-webview-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before Edge and WebView action planning.'
        }
        'control-panel-settings.source' = @{
            SourceId = 'control-panel-settings-source'
            ToolId = 'control-panel-settings'
            ModuleRelativePath = 'modules/Windows/control-panel-settings.psm1'
            SourceRelativePath = 'source-ultimate/6 Windows/15 Control Panel Settings.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = 'B78F643D21069F14E7E766769FB1EE15AEF974ABDF3CA010FE808D9EC162FB0B'
            CanonicalTextSha256 = 'F81FB649A4645A5145B43A051DDF8306145E64F1FCA5249F90B66BFDFA97BE83'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'control-panel-settings-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before Control Panel Settings action planning.'
        }
        'cleanup.source' = @{
            SourceId = 'cleanup-source'
            ToolId = 'cleanup'
            ModuleRelativePath = 'modules/Windows/cleanup.psm1'
            SourceRelativePath = 'source-ultimate/6 Windows/22 Cleanup.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '3419A995AD4483A145999B659268302F02BE982733DE831554ADA1C40F07CCAA'
            CanonicalTextSha256 = '13C3933AC95A9817E48C0FFA4971FB2CC2234F9783831C34675F9F529F2D507E'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimeVerification')
            ExternalHandling = 'ExternalRuntimeBlockedUntilDecoupled'
            ExternalModeTreatment = @('ExternalRuntimeStillBlocked', 'NeedsModuleDecoupling', 'DevelopmentOnlySourceParity')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @()
            OperationDescriptorId = 'cleanup-operation-summary'
            OperationDescriptorStatus = 'AvailableNotWired'
            Notes = 'Current runtime verifies this protected source before cleanup action planning.'
        }
        'timer-resolution-assistant.source' = @{
            SourceId = 'timer-resolution-assistant-source'
            ToolId = 'timer-resolution-assistant'
            ModuleRelativePath = 'modules/Advanced/timer-resolution-assistant.psm1'
            SourceRelativePath = 'source-ultimate/8 Advanced/6 Timer Resolution Assistant.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '883F7CF4E6179383DE02E44B94FFC8DAFD380246751F1B1D81CAB8800B1E8621'
            CanonicalTextSha256 = '46098A6B38BA04DA4A5A962EDC9B7EEBF2742A158845FA82C183D865133D2E73'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimePayloadGeneration', 'RuntimeVerification')
            ExternalHandling = 'ManifestOnly'
            ExternalModeTreatment = @('ManifestOnly', 'RuntimePayloadReady', 'DevelopmentOnlySourceParity', 'ExternalRuntimeCanExcludeSource')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @(
                @{
                    PayloadId = 'timer-resolution-csharp-service'
                    PayloadKind = 'Text'
                    HashMode = 'CanonicalText'
                    RuntimePayloadRelativePath = 'runtime-payloads/timer-resolution-assistant/SetTimerResolutionService.cs'
                    RuntimeWiringStatus = 'ReadyForExternalRuntime'
                    ExpectedSha256 = '34E5F2E420884FE59F5265F5963B943F9C38CC3D12EDEBF09843B85F95B40C77'
                    ExpectedLength = 8012
                    ExternalHandling = 'GeneratedRuntimePayloadAvailable'
                    Notes = 'The C# service payload is now available as a generated runtime payload; protected source remains internal-development parity/provenance input.'
                }
            )
            Notes = 'External runtime can use the generated C# service payload; internal development still records the protected source for parity and provenance.'
        }
        'defender-optimize-assistant.source' = @{
            SourceId = 'defender-optimize-assistant-source'
            ToolId = 'defender-optimize-assistant'
            ModuleRelativePath = 'modules/Advanced/defender-optimize-assistant.psm1'
            SourceRelativePath = 'source-ultimate/8 Advanced/7 Defender Optimize Assistant.ps1'
            SourceRole = 'ProtectedUltimateSource'
            RawSha256 = '512F12D805715E9232304ABE5BA400BE6B3965D63F77D3B39E4C304507BFB9B6'
            CanonicalTextSha256 = 'FA09439A4056CA16937B47AEA6D70092312513D92EC9DFA09CF62B1D625E0B92'
            HashMode = 'CanonicalText'
            RuntimeUse = @('SourceParityValidation', 'RuntimePayloadGeneration', 'RuntimeVerification')
            ExternalHandling = 'ManifestOnly'
            ExternalModeTreatment = @('ManifestOnly', 'RuntimePayloadReady', 'DevelopmentOnlySourceParity', 'ExternalRuntimeCanExcludeSource')
            CustomerVisible = $false
            CurrentInternalSourceRequired = $true
            HighRiskBlocker = $false
            PayloadBlockers = @(
                @{
                    PayloadId = 'defender-optimize-apply-script'
                    PayloadKind = 'Text'
                    HashMode = 'CanonicalText'
                    RuntimePayloadRelativePath = 'runtime-payloads/defender-optimize-assistant/defenderoptimize.ps1'
                    RuntimeWiringStatus = 'ReadyForExternalRuntime'
                    ExpectedSha256 = 'DB0D5742D39127A2349953905A3647699023A942FE3FE2A37B264E7894444611'
                    ExpectedLength = 10222
                    ExternalHandling = 'GeneratedRuntimePayloadAvailable'
                    Notes = 'The Defender Optimize Apply script is now available as a generated runtime payload; protected source remains internal-development parity/provenance input.'
                }
                @{
                    PayloadId = 'defender-optimize-default-script'
                    PayloadKind = 'Text'
                    HashMode = 'CanonicalText'
                    RuntimePayloadRelativePath = 'runtime-payloads/defender-optimize-assistant/defenderdefault.ps1'
                    RuntimeWiringStatus = 'ReadyForExternalRuntime'
                    ExpectedSha256 = '71885EFD529F13EF3C42C21C25F2040C6D38FD7F98F94B60EF9B23760C083948'
                    ExpectedLength = 9814
                    ExternalHandling = 'GeneratedRuntimePayloadAvailable'
                    Notes = 'The Defender Optimize Default script is now available as a generated runtime payload; protected source remains internal-development parity/provenance input.'
                }
            )
            Notes = 'External runtime can use the generated Defender Apply and Default script payloads; internal development still records the protected source for parity and provenance.'
        }
    }
}
